In [1]:
import pandas as pd

# Cargar archivo XPT
df = pd.read_sas("dataset.xpt", format="xport")

In [2]:
# Ver nombres de columnas
print(df.columns)

Index(['SEQN', 'WTSB2YR', 'URXBP3', 'URDBP3LC', 'URXBPH', 'URDBPHLC', 'URXBPF',
       'URDBPFLC', 'URXBPS', 'URDBPSLC', 'URXTLC', 'URDTLCLC', 'URXTRS',
       'URDTRSLC', 'URXBUP', 'URDBUPLC', 'URXEPB', 'URDEPBLC', 'URXMPB',
       'URDMPBLC', 'URXPPB', 'URDPPBLC', 'URX14D', 'URD14DLC', 'URXDCB',
       'URDDCBLC'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2986 entries, 0 to 2985
Data columns (total 26 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      2986 non-null   float64
 1   WTSB2YR   2986 non-null   float64
 2   URXBP3    2759 non-null   float64
 3   URDBP3LC  2759 non-null   float64
 4   URXBPH    2758 non-null   float64
 5   URDBPHLC  2758 non-null   float64
 6   URXBPF    2757 non-null   float64
 7   URDBPFLC  2757 non-null   float64
 8   URXBPS    2756 non-null   float64
 9   URDBPSLC  2756 non-null   float64
 10  URXTLC    2761 non-null   float64
 11  URDTLCLC  2761 non-null   float64
 12  URXTRS    2740 non-null   float64
 13  URDTRSLC  2740 non-null   float64
 14  URXBUP    2761 non-null   float64
 15  URDBUPLC  2761 non-null   float64
 16  URXEPB    2759 non-null   float64
 17  URDEPBLC  2759 non-null   float64
 18  URXMPB    2743 non-null   float64
 19  URDMPBLC  2743 non-null   float64
 20  URXPPB    2760 non-null   float64
 21  URDPPBLC  2760 non-null   float64
 22  URX14D    2759 non-null   float64
 23  URD14DLC  2759 non-null   float64
 24  URXDCB    2760 non-null   float64
 25  URDDCBLC  2760 non-null   float64
dtypes: float64(26)
memory usage: 606.7 KB

In [4]:
# columnas de concentraciones
cols_values = [col for col in df.columns if col.startswith("URX")]

# columnas de flags (LOD)
cols_flags = [col for col in df.columns if col.endswith("LC")]

In [5]:
df[cols_flags].value_counts()

URDBP3LC      URDBPHLC      URDBPFLC      URDBPSLC      URXTLC  URDTLCLC      URDTRSLC      URDBUPLC      URDEPBLC      URDMPBLC      URDPPBLC      URD14DLC      URDDCBLC
5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  0.07    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79    190
                            1.000000e+00  5.397605e-79  0.07    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79    183
                            5.397605e-79  5.397605e-79  0.07    1.000000e+00  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79    131
                                                                              5.397605e-79  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79    121
                            1.000000e+00  5.397605e-79  0.07    1.000000e+00  5.397605e-79  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79    114
                                                                                                                                                                                 ...
                            5.397605e-79  5.397605e-79  0.07    1.000000e+00  5.397605e-79  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  5.397605e-79  5.397605e-79      1
              1.000000e+00  1.000000e+00  5.397605e-79  0.20    5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79      1
              5.397605e-79  5.397605e-79  5.397605e-79  2.20    5.397605e-79  5.397605e-79  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79      1
                            1.000000e+00  1.000000e+00  0.50    5.397605e-79  5.397605e-79  1.000000e+00  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79  5.397605e-79      1
              1.000000e+00  1.000000e+00  1.000000e+00  0.07    1.000000e+00  5.397605e-79  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  5.397605e-79  1.000000e+00      1
Name: count, Length: 593, dtype: int64

In [6]:
import numpy as np

# convertir valores bajo LOD a NaN (o a LOD/√2 dependiendo del análisis)
for col in cols_values:
    flag_col = col.replace("URX", "URD") + "LC"
    if flag_col in df.columns:
        df.loc[df[flag_col] == 1, col] = np.nan

In [7]:
df[cols_values].describe()

,URXBP3,URXBPH,URXBPF,URXBPS,URXTLC,URXTRS,URXBUP,URXEPB,URXMPB,URXPPB,URX14D,URXDCB
count,2712.000000,2372.000000,1441.000000,2441.000000,882.000000,1153.000000,457.000000,1154.000000,2698.000000,2629.000000,2701.000000,2453.000000
mean,181.353540,1.819393,4.623664,2.320934,3.834014,108.282134,2.809628,47.087955,193.024240,35.936402,130.846501,4.041256
std,1197.714191,9.351129,25.887575,29.070773,13.048369,260.563500,8.533964,173.826538,819.573109,178.669316,958.048029,24.473717
min,0.400000,0.200000,0.200000,0.100000,0.100000,1.700000,0.100000,1.000000,1.000000,0.100000,0.100000,0.100000
25%,4.100000,0.500000,0.300000,0.300000,0.100000,2.800000,0.200000,1.800000,7.200000,0.700000,0.800000,0.300000
50%,11.200000,0.900000,0.600000,0.600000,0.200000,6.200000,0.300000,4.600000,25.300000,2.700000,2.100000,0.500000
75%,39.100000,1.600000,1.600000,1.300000,0.800000,79.900000,1.600000,20.475000,115.750000,17.200000,10.000000,1.000000
max,30900.000000,408.000000,727.000000,1220.000000,175.000000,2820.000000,79.100000,2290.000000,21100.000000,6750.000000,23500.000000,575.000000

## COLOCAR NOMBRES DE VARIABLES ORIGINALES ##

In [9]:
# Diccionario de mapeo: columna original -> nombre descriptivo
rename_dict = {
    "URXBP3": "Urinary Benzophenone-3 (ng/mL)",
    "URXBPH": "Urinary Bisphenol A (ng/mL)",
    "URXBPF": "Urinary Bisphenol F (ng/mL)",
    "URXBPS": "Urinary Bisphenol S (ng/mL)",
    "URXTLC": "Urinary Triclocarban (ng/mL)",
    "URXTRS": "Urinary Triclosan (ng/mL)",
    "URXBUP": "Urinary Butyl paraben (ng/mL)",
    "URXEPB": "Urinary Ethyl paraben (ng/mL)",
    "URXMPB": "Urinary Methyl paraben (ng/mL)",
    "URXPPB": "Urinary Propyl paraben (ng/mL)",
    "URXDCB": "Urinary 2,4-dichlorophenol (ng/mL)",
    "URX14D": "Urinary 2,5-dichlorophenol (ng/mL)"
}

In [10]:
df = df.rename(columns=rename_dict)

In [11]:
print(df.columns)

Index(['SEQN', 'WTSB2YR', 'Urinary Benzophenone-3 (ng/mL)', 'URDBP3LC',
       'Urinary Bisphenol A (ng/mL)', 'URDBPHLC',
       'Urinary Bisphenol F (ng/mL)', 'URDBPFLC',
       'Urinary Bisphenol S (ng/mL)', 'URDBPSLC',
       'Urinary Triclocarban (ng/mL)', 'URDTLCLC', 'Urinary Triclosan (ng/mL)',
       'URDTRSLC', 'Urinary Butyl paraben (ng/mL)', 'URDBUPLC',
       'Urinary Ethyl paraben (ng/mL)', 'URDEPBLC',
       'Urinary Methyl paraben (ng/mL)', 'URDMPBLC',
       'Urinary Propyl paraben (ng/mL)', 'URDPPBLC',
       'Urinary 2,5-dichlorophenol (ng/mL)', 'URD14DLC',
       'Urinary 2,4-dichlorophenol (ng/mL)', 'URDDCBLC'],
      dtype='str')

In [13]:
df[df.columns].describe()

,SEQN,WTSB2YR,Urinary Benzophenone-3 (ng/mL),URDBP3LC,Urinary Bisphenol A (ng/mL),URDBPHLC,Urinary Bisphenol F (ng/mL),URDBPFLC,Urinary Bisphenol S (ng/mL),URDBPSLC,...,Urinary Ethyl paraben (ng/mL),URDEPBLC,Urinary Methyl paraben (ng/mL),URDMPBLC,Urinary Propyl paraben (ng/mL),URDPPBLC,"Urinary 2,5-dichlorophenol (ng/mL)",URD14DLC,"Urinary 2,4-dichlorophenol (ng/mL)",URDDCBLC
count,2986.000000,2.986000e+03,2712.000000,2.759000e+03,2372.000000,2.758000e+03,1441.000000,2.757000e+03,2441.000000,2.756000e+03,...,1154.000000,2.759000e+03,2698.000000,2.743000e+03,2629.000000,2.760000e+03,2701.000000,2.759000e+03,2453.000000,2.760000e+03
mean,98345.420965,1.035708e+05,181.353540,1.703516e-02,1.819393,1.399565e-01,4.623664,4.773304e-01,2.320934,1.142961e-01,...,47.087955,5.817325e-01,193.024240,1.640540e-02,35.936402,4.746377e-02,130.846501,2.102211e-02,4.041256,1.112319e-01
std,2657.279434,1.324530e+05,1197.714191,1.294258e-01,9.351129,3.470048e-01,25.887575,4.995764e-01,29.070773,3.182283e-01,...,173.826538,4.933640e-01,819.573109,1.270517e-01,178.669316,2.126672e-01,958.048029,1.434839e-01,24.473717,3.144760e-01
min,93706.000000,5.397605e-79,0.400000,5.397605e-79,0.200000,5.397605e-79,0.200000,5.397605e-79,0.100000,5.397605e-79,...,1.000000,5.397605e-79,1.000000,5.397605e-79,0.100000,5.397605e-79,0.100000,5.397605e-79,0.100000,5.397605e-79
25%,96004.500000,3.432727e+04,4.100000,5.397605e-79,0.500000,5.397605e-79,0.300000,5.397605e-79,0.300000,5.397605e-79,...,1.800000,5.397605e-79,7.200000,5.397605e-79,0.700000,5.397605e-79,0.800000,5.397605e-79,0.300000,5.397605e-79
50%,98353.500000,6.121458e+04,11.200000,5.397605e-79,0.900000,5.397605e-79,0.600000,5.397605e-79,0.600000,5.397605e-79,...,4.600000,1.000000e+00,25.300000,5.397605e-79,2.700000,5.397605e-79,2.100000,5.397605e-79,0.500000,5.397605e-79
75%,100656.250000,1.126775e+05,39.100000,5.397605e-79,1.600000,5.397605e-79,1.600000,1.000000e+00,1.300000,5.397605e-79,...,20.475000,1.000000e+00,115.750000,5.397605e-79,17.200000,5.397605e-79,10.000000,5.397605e-79,1.000000,5.397605e-79
max,102955.000000,1.395405e+06,30900.000000,1.000000e+00,408.000000,1.000000e+00,727.000000,1.000000e+00,1220.000000,1.000000e+00,...,2290.000000,1.000000e+00,21100.000000,1.000000e+00,6750.000000,1.000000e+00,23500.000000,1.000000e+00,575.000000,1.000000e+00